In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_excel('BoneCancerRaw.xlsx')
df2 = pd.read_excel('BoneCancerConvert.xlsx')

In [3]:
print(df1.shape)
print(df2.shape)

(1309, 6)
(1309, 4)


In [4]:
frame = [df2, df1]
df = pd.concat(frame, axis=1)
df_clean = df.drop(columns=['Probe ID', 'Species', 'Gene Name', 'ID', 'Gene Symbol'])
df_clean

Entrez ID  GSM921514   GSM92151  GSM921516  GSM921517
0           780  10.678832  10.291389   9.608725   9.412715
1          5982   9.499689   8.981216   9.385408   9.868524
2          3310   5.848989   5.380187   5.566532   5.577159
3          7849   8.189986   8.431688   8.332415   8.084233
4          2978   3.519274   3.453561   4.207195   3.386633
...         ...        ...        ...        ...        ...
1304      64866   4.679561   4.855678   6.055085   4.430294
1305       9706   5.666462   5.683198   6.081623   5.394488
1306       9498   5.589828   5.233311   7.455269   7.145090
1307      85464   6.190972   6.977493   5.725543   5.968132
1308     133874   5.079534   4.924706   5.054912   5.306256

[1309 rows x 5 columns]

In [17]:
df_clean.to_excel("BoneCancerStandardize.xlsx", index=False)

### Dataset Preprocessing

In [5]:
data = pd.read_excel("BoneCancerStandardize.xlsx")
data.head()

Entrez ID  GSM921514   GSM92151  GSM921516  GSM921517
0        780  10.678832  10.291389   9.608725   9.412715
1       5982   9.499689   8.981216   9.385408   9.868524
2       3310   5.848989   5.380187   5.566532   5.577159
3       7849   8.189986   8.431688   8.332415   8.084233
4       2978   3.519274   3.453561   4.207195   3.386633

In [6]:
data.shape

(1309, 5)

In [7]:
data.columns

Index(['Entrez ID', 'GSM921514', 'GSM92151', 'GSM921516', 'GSM921517'], dtype='object')

In [8]:
data.dtypes

Entrez ID      int64
GSM921514    float64
GSM92151     float64
GSM921516    float64
GSM921517    float64
dtype: object

In [9]:
data = data.astype({"Entrez ID": float})
data.dtypes

Entrez ID    float64
GSM921514    float64
GSM92151     float64
GSM921516    float64
GSM921517    float64
dtype: object

In [10]:
data.isnull().sum()

Entrez ID    0
GSM921514    0
GSM92151     0
GSM921516    0
GSM921517    0
dtype: int64

In [11]:
from sklearn import preprocessing

In [12]:
x_array = np.array(data["GSM921514"])
normalized = preprocessing.normalize([x_array])
normalized

array([[0.0514499 , 0.04576887, 0.02818003, ..., 0.02693141, 0.02982769,
        0.02447285]])

In [13]:
x_array = np.array(data["GSM92151"])
normalized = preprocessing.normalize([x_array])
normalized

array([[0.04977201, 0.04343565, 0.02602008, ..., 0.02530974, 0.03374509,
        0.02381724]])

In [14]:
x_array = np.array(data["GSM921516"])
normalized = preprocessing.normalize([x_array])
normalized

array([[0.04600891, 0.04493961, 0.02665391, ..., 0.03569763, 0.02741529,
        0.02420414]])

In [15]:
x_array = np.array(data["GSM921517"])
normalized = preprocessing.normalize([x_array])
normalized

array([[0.04511043, 0.04729489, 0.02672853, ..., 0.03424284, 0.02860227,
        0.02543023]])

#### Exploratory Data Analysis